Sys.setlocale(category = "LC_ALL", locale = "C")
datRaw <- read.table("./coursera/data//household_power_consumption.txt", sep = ";", header = TRUE, stringsAsFactors = FALSE, na.strings = "?")
datData <- subset(datRaw, Date %in% c("1/2/2007","2/2/2007"))
datData$Date <- as.Date(datData$Date,"%d/%m/%Y")
datData$Time <- strptime(paste(datData$Date, datData$Time), "%Y-%m-%d %H:%M:%S")
png(filename = "plot4.png", width=480, height = 480)

par(mfrow = c(2,2))
plot(datData$Time, datData$Global_active_power,type = "l", xlab = "", ylab = "Global Active Power")
plot(datData$Time, datData$Voltage,type = "l", xlab = "datetime", ylab = "Voltage")
plot(datData$Time, datData$Sub_metering_1, type = "l", col="Black",xlab = "", ylab = "Energy sub metering")
lines(datData$Time, datData$Sub_metering_2, col= "Red")
lines(datData$Time, datData$Sub_metering_3, col= "Blue")
legend("topright", col = c("Black", "Red", "Blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, bty = "n")
plot(datData$Time, datData$Global_reactive_power,type = "l", xlab = "datetime", ylab = "Global_reactive_power")

dev.off()
